use sockwho_common::{SockaddrEvent, SocketStateEvent};

/// An event generated by our eBPF probes.
#[derive(Clone, Debug)]
pub enum BpfEvent {
    /// An event that uses a socket address. e.g. a call to bind(2).
    Sockaddr(SockaddrEvent),

    /// An event that changes the state of a socket.
    SocketState(SocketStateEvent),
}

impl From<SockaddrEvent> for BpfEvent {
    fn from(event: SockaddrEvent) -> Self {
        Self::Sockaddr(event)
    }
}

impl From<SocketStateEvent> for BpfEvent {
    fn from(event: SocketStateEvent) -> Self {
        Self::SocketState(event)
    }
}
