use sockwho_common::SockaddrEvent;

/// An event generated by our eBPF probes.
#[derive(Clone, Debug)]
pub enum BpfEvent {
    /// An address resolution event.
    Sockaddr(SockaddrEvent),
}

impl From<SockaddrEvent> for BpfEvent {
    fn from(event: SockaddrEvent) -> Self {
        Self::Sockaddr(event)
    }
}
